/*
 * Copyright 2025-2026 the Kairo authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.kairo.api.team;

import io.kairo.api.Experimental;
import io.kairo.api.agent.Agent;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * A team of agents collaborating via a shared {@link MessageBus}.
 *
 * <p>Task-board semantics that the legacy v0.9 {@code Team} aggregated directly are now an
 * implementation detail of the concrete {@link TeamCoordinator} that drives the team.
 *
 * @since v0.10
 */
@Experimental("Team aggregate root; introduced in v0.10, targeting stabilization in v1.2.0")
public class Team {

    private final String teamId;
    private final String name;
    private final String goal;
    private final List<Agent> agents;
    private final MessageBus messageBus;
    private final TeamLifecycleStatus status;
    private final Map<String, Object> metadata;
    private final Instant createdAt;

    /**
     * Full constructor.
     *
     * @param teamId unique identifier (generated by TeamManager)
     * @param name human-readable team name
     * @param goal what this team is trying to accomplish
     * @param agents initial agent roster; defensively copied
     * @param messageBus message bus for inter-agent communication
     * @param status lifecycle status
     * @param metadata extensible key-value metadata
     * @param createdAt creation timestamp
     */
    public Team(
            String teamId,
            String name,
            String goal,
            List<Agent> agents,
            MessageBus messageBus,
            TeamLifecycleStatus status,
            Map<String, Object> metadata,
            Instant createdAt) {
        this.teamId = Objects.requireNonNull(teamId, "teamId must not be null");
        this.name = Objects.requireNonNull(name, "name must not be null");
        this.goal = goal == null ? "" : goal;
        this.agents = List.copyOf(Objects.requireNonNull(agents, "agents must not be null"));
        this.messageBus = Objects.requireNonNull(messageBus, "messageBus must not be null");
        this.status = Objects.requireNonNull(status, "status must not be null");
        this.metadata = metadata == null ? Map.of() : Map.copyOf(metadata);
        this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
    }

    /**
     * Backward-compatible constructor. Sets teamId=name, goal="", status=ACTIVE.
     *
     * @deprecated Use the full constructor for new code.
     */
    @Deprecated(since = "1.2.0", forRemoval = false)
    public Team(String name, List<Agent> agents, MessageBus messageBus) {
        this(
                name,
                name,
                "",
                agents,
                messageBus,
                TeamLifecycleStatus.ACTIVE,
                Map.of(),
                Instant.now());
    }

    /** Unique team identifier. */
    public String teamId() {
        return teamId;
    }

    /** Human-readable team name. */
    public String name() {
        return name;
    }

    /** What this team is trying to accomplish. */
    public String goal() {
        return goal;
    }

    /** The agents in this team (immutable view). */
    public List<Agent> agents() {
        return agents;
    }

    /** The message bus for inter-agent communication. */
    public MessageBus messageBus() {
        return messageBus;
    }

    /** Lifecycle status. */
    public TeamLifecycleStatus status() {
        return status;
    }

    /** Extensible key-value metadata. */
    public Map<String, Object> metadata() {
        return metadata;
    }

    /** Creation timestamp. */
    public Instant createdAt() {
        return createdAt;
    }
}
