/*
 * Copyright 2025 Kairo Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.kairo.observability;

import io.opentelemetry.api.common.AttributeKey;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * OpenTelemetry GenAI semantic convention attribute keys.
 *
 * <p>Centralizes all GenAI-specific attribute keys used by the Kairo observability layer. The OTel
 * GenAI semantic conventions are still experimental and may change package names or key formats —
 * centralizing here means <strong>only this one file</strong> needs to be updated when the semconv
 * stabilizes.
 *
 * <p>This class also provides a {@linkplain #kairoKeyToOTel(String) translation map} from Kairo's
 * internal short key strings (e.g. {@code "token.input"}) to the corresponding OTel {@link
 * AttributeKey} constants. This is used by {@code OTelSpan.setAttribute()} to bridge the Kairo
 * tracing API to OTel attributes.
 *
 * @see <a href="https://opentelemetry.io/docs/specs/semconv/gen-ai/">OTel GenAI Semantic
 *     Conventions</a>
 */
public final class GenAiSemanticAttributes {

    private GenAiSemanticAttributes() {}

    // ---------------------------------------------------------------------------
    // Token usage
    // ---------------------------------------------------------------------------

    /** Number of input (prompt) tokens consumed by a model call. */
    public static final AttributeKey<Long> USAGE_INPUT_TOKENS =
            AttributeKey.longKey("gen_ai.usage.input_tokens");

    /** Number of output (completion) tokens generated by a model call. */
    public static final AttributeKey<Long> USAGE_OUTPUT_TOKENS =
            AttributeKey.longKey("gen_ai.usage.output_tokens");

    /** Number of tokens served from prompt cache. */
    public static final AttributeKey<Long> USAGE_CACHE_READ_TOKENS =
            AttributeKey.longKey("gen_ai.usage.cache_read_tokens");

    /** Number of tokens written to prompt cache. */
    public static final AttributeKey<Long> USAGE_CACHE_CREATION_TOKENS =
            AttributeKey.longKey("gen_ai.usage.cache_creation_tokens");

    // ---------------------------------------------------------------------------
    // Tool execution
    // ---------------------------------------------------------------------------

    /** Name of the tool being executed. */
    public static final AttributeKey<String> TOOL_NAME = AttributeKey.stringKey("gen_ai.tool.name");

    /** Whether the tool execution completed successfully. */
    public static final AttributeKey<Boolean> TOOL_SUCCESS =
            AttributeKey.booleanKey("gen_ai.tool.success");

    /** Wall-clock duration of the tool execution in milliseconds. */
    public static final AttributeKey<Long> TOOL_DURATION_MS =
            AttributeKey.longKey("gen_ai.tool.duration_ms");

    // ---------------------------------------------------------------------------
    // Agent
    // ---------------------------------------------------------------------------

    /** Name of the agent being traced. */
    public static final AttributeKey<String> AGENT_NAME =
            AttributeKey.stringKey("gen_ai.agent.name");

    /** Zero-based iteration index within the agent loop. */
    public static final AttributeKey<Long> AGENT_ITERATION =
            AttributeKey.longKey("gen_ai.agent.iteration");

    /** Model identifier used for the request. */
    public static final AttributeKey<String> MODEL_NAME =
            AttributeKey.stringKey("gen_ai.request.model");

    /** Number of messages sent to the model. */
    public static final AttributeKey<Long> MESSAGE_COUNT =
            AttributeKey.longKey("gen_ai.request.message_count");

    // ---------------------------------------------------------------------------
    // Compaction
    // ---------------------------------------------------------------------------

    /** Compaction strategy used (e.g. "summarize", "truncate"). */
    public static final AttributeKey<String> COMPACTION_STRATEGY =
            AttributeKey.stringKey("gen_ai.compaction.strategy");

    /** Number of tokens reclaimed by compaction. */
    public static final AttributeKey<Long> COMPACTION_TOKENS_SAVED =
            AttributeKey.longKey("gen_ai.compaction.tokens_saved");

    // ---------------------------------------------------------------------------
    // Cache detection (for CacheBreakDetector)
    // ---------------------------------------------------------------------------

    /** Cache hit ratio (0.0 – 1.0). */
    public static final AttributeKey<Double> CACHE_HIT_RATIO =
            AttributeKey.doubleKey("gen_ai.cache.hit_ratio");

    /** Whether a cache break was detected. */
    public static final AttributeKey<Boolean> CACHE_BROKEN =
            AttributeKey.booleanKey("gen_ai.cache.broken");

    /** Comma-separated reasons for cache break. */
    public static final AttributeKey<String> CACHE_BREAK_REASONS =
            AttributeKey.stringKey("gen_ai.cache.break_reasons");

    // ---------------------------------------------------------------------------
    // Standard OTel exception keys (not GenAI-specific, included for completeness)
    // ---------------------------------------------------------------------------

    /** Fully-qualified exception class name. */
    public static final AttributeKey<String> EXCEPTION_TYPE =
            AttributeKey.stringKey("exception.type");

    /** Exception message string. */
    public static final AttributeKey<String> EXCEPTION_MESSAGE =
            AttributeKey.stringKey("exception.message");

    // ---------------------------------------------------------------------------
    // Kairo key → OTel AttributeKey mapping
    // ---------------------------------------------------------------------------

    /**
     * Unmodifiable mapping from Kairo's short attribute key strings to OTel {@link AttributeKey}
     * constants. Used by {@code OTelSpan.setAttribute()} to translate between the two systems.
     *
     * <p>Keys follow the pattern used by {@link io.kairo.api.tracing.Tracer} default methods (e.g.
     * {@code "token.input"}, {@code "tool.name"}).
     */
    private static final Map<String, AttributeKey<?>> KAIRO_KEY_MAP;

    static {
        Map<String, AttributeKey<?>> map = new HashMap<>();

        // Token usage
        map.put("token.input", USAGE_INPUT_TOKENS);
        map.put("token.output", USAGE_OUTPUT_TOKENS);
        map.put("token.cache_read", USAGE_CACHE_READ_TOKENS);
        map.put("token.cache_write", USAGE_CACHE_CREATION_TOKENS);

        // Tool execution
        map.put("tool.name", TOOL_NAME);
        map.put("tool.success", TOOL_SUCCESS);
        map.put("tool.duration_ms", TOOL_DURATION_MS);

        // Agent
        map.put("agent.name", AGENT_NAME);
        map.put("agent.iteration", AGENT_ITERATION);
        map.put("model.name", MODEL_NAME);
        map.put("message.count", MESSAGE_COUNT);

        // Compaction
        map.put("compaction.strategy", COMPACTION_STRATEGY);
        map.put("compaction.tokens_saved", COMPACTION_TOKENS_SAVED);

        // Cache
        map.put("cache.hit_ratio", CACHE_HIT_RATIO);
        map.put("cache.broken", CACHE_BROKEN);
        map.put("cache.break_reasons", CACHE_BREAK_REASONS);

        // Exception
        map.put("exception.type", EXCEPTION_TYPE);
        map.put("exception.message", EXCEPTION_MESSAGE);

        KAIRO_KEY_MAP = Collections.unmodifiableMap(map);
    }

    /**
     * Look up the OTel {@link AttributeKey} for a Kairo short key string.
     *
     * @param kairoKey the Kairo-internal attribute key (e.g. {@code "token.input"})
     * @return the corresponding OTel {@link AttributeKey}, or {@code null} if no mapping exists
     */
    public static AttributeKey<?> kairoKeyToOTel(String kairoKey) {
        return KAIRO_KEY_MAP.get(kairoKey);
    }

    /**
     * Return an unmodifiable view of the full Kairo key → OTel key mapping.
     *
     * @return unmodifiable map of all registered key translations
     */
    public static Map<String, AttributeKey<?>> allMappings() {
        return KAIRO_KEY_MAP;
    }
}
